package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ActionCall_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IHasArguments_BehaviorDescriptor {
  public ActionCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.ActionCall";
  }
}
