package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new ActionDefinition_BehaviorDescriptor();
      case 14:
        return new Parameter_BehaviorDescriptor();
      case 4:
        return new Category_BehaviorDescriptor();
      case 12:
        return new OptionParameter_BehaviorDescriptor();
      case 11:
        return new Option_BehaviorDescriptor();
      case 18:
        return new TaskDefinition_BehaviorDescriptor();
      case 10:
        return new NamedTaskDefinition_BehaviorDescriptor();
      case 15:
        return new Profile_BehaviorDescriptor();
      case 7:
        return new ContextInstance_BehaviorDescriptor();
      case 8:
        return new EventDefinition_BehaviorDescriptor();
      case 16:
        return new StateDefinition_BehaviorDescriptor();
      case 6:
        return new ContextDefinition_BehaviorDescriptor();
      case 19:
        return new TaskReference_BehaviorDescriptor();
      case 0:
        return new ActionCall_BehaviorDescriptor();
      case 2:
        return new Argument_BehaviorDescriptor();
      case 20:
        return new Value_BehaviorDescriptor();
      case 9:
        return new IntegerValue_BehaviorDescriptor();
      case 17:
        return new StringValue_BehaviorDescriptor();
      case 3:
        return new BooleanValue_BehaviorDescriptor();
      case 13:
        return new OptionValue_BehaviorDescriptor();
      case 22:
        return new Variable_BehaviorDescriptor();
      case 23:
        return new VariableGroup_BehaviorDescriptor();
      case 21:
        return new ValueOrVariable_BehaviorDescriptor();
      case 5:
        return new CategoryGroup_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"stillmancorp.dsl.tasker.structure.ActionCall", "stillmancorp.dsl.tasker.structure.ActionDefinition", "stillmancorp.dsl.tasker.structure.Argument", "stillmancorp.dsl.tasker.structure.BooleanValue", "stillmancorp.dsl.tasker.structure.Category", "stillmancorp.dsl.tasker.structure.CategoryGroup", "stillmancorp.dsl.tasker.structure.ContextDefinition", "stillmancorp.dsl.tasker.structure.ContextInstance", "stillmancorp.dsl.tasker.structure.EventDefinition", "stillmancorp.dsl.tasker.structure.IntegerValue", "stillmancorp.dsl.tasker.structure.NamedTaskDefinition", "stillmancorp.dsl.tasker.structure.Option", "stillmancorp.dsl.tasker.structure.OptionParameter", "stillmancorp.dsl.tasker.structure.OptionValue", "stillmancorp.dsl.tasker.structure.Parameter", "stillmancorp.dsl.tasker.structure.Profile", "stillmancorp.dsl.tasker.structure.StateDefinition", "stillmancorp.dsl.tasker.structure.StringValue", "stillmancorp.dsl.tasker.structure.TaskDefinition", "stillmancorp.dsl.tasker.structure.TaskReference", "stillmancorp.dsl.tasker.structure.Value", "stillmancorp.dsl.tasker.structure.ValueOrVariable", "stillmancorp.dsl.tasker.structure.Variable", "stillmancorp.dsl.tasker.structure.VariableGroup"};
}
