package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class BooleanValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public BooleanValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.BooleanValue";
  }
}
