package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CategoryGroup_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CategoryGroup_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.CategoryGroup";
  }
}
