package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ContextInstance_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ContextInstance_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.ContextInstance";
  }
}
