package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class EventDefinition_BehaviorDescriptor extends ContextDefinition_BehaviorDescriptor {
  public EventDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.EventDefinition";
  }
}
