package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class NamedTaskDefinition_BehaviorDescriptor extends TaskDefinition_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public NamedTaskDefinition_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.NamedTaskDefinition";
  }
}
