package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class OptionParameter_BehaviorDescriptor extends Parameter_BehaviorDescriptor {
  public OptionParameter_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.OptionParameter";
  }
}
