package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class OptionValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public OptionValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.OptionValue";
  }
}
