package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class StateDefinition_BehaviorDescriptor extends ContextDefinition_BehaviorDescriptor {
  public StateDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.StateDefinition";
  }
}
