package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TaskReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TaskReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.TaskReference";
  }
}
