package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TaskDefinition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TaskDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.TaskDefinition";
  }
}
