package stillmancorp.dsl.tasker.behavior;

/*Generated by MPS */


public class ValueOrVariable_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public ValueOrVariable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stillmancorp.dsl.tasker.structure.ValueOrVariable";
  }
}
