package stillmancorp.dsl.tasker.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ActionDefinition_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Category_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CategoryGroup_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ContextInstance_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Option_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new OptionParameter_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Parameter_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Profile_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new TaskReference_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new Variable_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new VariableGroup_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"stillmancorp.dsl.tasker.structure.ActionDefinition", "stillmancorp.dsl.tasker.structure.Category", "stillmancorp.dsl.tasker.structure.CategoryGroup", "stillmancorp.dsl.tasker.structure.ContextInstance", "stillmancorp.dsl.tasker.structure.Option", "stillmancorp.dsl.tasker.structure.OptionParameter", "stillmancorp.dsl.tasker.structure.Parameter", "stillmancorp.dsl.tasker.structure.Profile", "stillmancorp.dsl.tasker.structure.TaskReference", "stillmancorp.dsl.tasker.structure.Variable", "stillmancorp.dsl.tasker.structure.VariableGroup"};
}
