package stillmancorp.dsl.tasker.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TaskerDataTypes {
  str("string", "str"),
  integer("integer", "int"),
  bool("boolean", "bool"),
  icon("icon", "icon");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TaskerDataTypes> getConstants() {
    List<TaskerDataTypes> list = ListSequence.fromList(new LinkedList<TaskerDataTypes>());
    ListSequence.fromList(list).addElement(TaskerDataTypes.str);
    ListSequence.fromList(list).addElement(TaskerDataTypes.integer);
    ListSequence.fromList(list).addElement(TaskerDataTypes.bool);
    ListSequence.fromList(list).addElement(TaskerDataTypes.icon);
    return list;
  }

  public static TaskerDataTypes getDefault() {
    return null;
  }

  public static TaskerDataTypes parseValue(String value) {
    if (value == null) {
      return TaskerDataTypes.getDefault();
    }
    if (value.equals(TaskerDataTypes.str.getValueAsString())) {
      return TaskerDataTypes.str;
    }
    if (value.equals(TaskerDataTypes.integer.getValueAsString())) {
      return TaskerDataTypes.integer;
    }
    if (value.equals(TaskerDataTypes.bool.getValueAsString())) {
      return TaskerDataTypes.bool;
    }
    if (value.equals(TaskerDataTypes.icon.getValueAsString())) {
      return TaskerDataTypes.icon;
    }
    return TaskerDataTypes.getDefault();
  }

  private String myValue;

  TaskerDataTypes(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
