package stillmancorp.dsl.tasker.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TaskerPrivacy {
  pub("public", "public"),
  priv("private", "private");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TaskerPrivacy> getConstants() {
    List<TaskerPrivacy> list = ListSequence.fromList(new LinkedList<TaskerPrivacy>());
    ListSequence.fromList(list).addElement(TaskerPrivacy.pub);
    ListSequence.fromList(list).addElement(TaskerPrivacy.priv);
    return list;
  }

  public static TaskerPrivacy getDefault() {
    return TaskerPrivacy.pub;
  }

  public static TaskerPrivacy parseValue(String value) {
    if (value == null) {
      return TaskerPrivacy.getDefault();
    }
    if (value.equals(TaskerPrivacy.pub.getValueAsString())) {
      return TaskerPrivacy.pub;
    }
    if (value.equals(TaskerPrivacy.priv.getValueAsString())) {
      return TaskerPrivacy.priv;
    }
    return TaskerPrivacy.getDefault();
  }

  private String myValue;

  TaskerPrivacy(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
