package stillmancorp.dsl.tasker.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("a318723a-cdc7-4b10-863a-42eb021730b2(stillmancorp.dsl.tasker)"), PersistenceFacade.getInstance().createModelReference("r:7b7d240e-af7c-4889-ab03-0b451be4f52c(stillmancorp.dsl.tasker.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new MakeOptional_Intention());
  }
}
